# image will be published to ghcr.io/<user>/<name>
name: meow-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: rpm-ostree
    repos:
      - https://download.opensuse.org/repositories/home:tschmitz:activate-linux/Fedora_Rawhide/home:tschmitz:activate-linux.repo
      - https://copr.fedorainfracloud.org/coprs/g/kernel-vanilla/mainline/repo/fedora-41/group_kernel-vanilla-mainline-fedora-41.repo
    install:
      - activate-linux

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - optimot.sh
      # - HuionTablet_LinuxDriver_v15.0.0.162.x86_64/install.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

